# package.yaml
name: core-sdk
version: 1.3.1
description: Patterns and templates for creating reusable core libraries that can be shared across MCP servers, REST APIs, and client applications
author: Patrick Michaelsen
license: MIT
homepage: https://github.com/prmichaelsen/acp-core-sdk
repository: https://github.com/prmichaelsen/acp-core-sdk.git

# Release configuration
release:
  branch: main

# Package contents
# Add files here as you create them
# Use @acp.pattern-create, @acp.command-create, @acp.design-create
# These commands automatically update this section
contents:
  patterns:
    - name: core-sdk.service-base.md
      description: Base service class pattern with lifecycle management, configuration, and common functionality
      category: Service Layer
      
    - name: core-sdk.service-interface.md
      description: Service interface pattern for dependency injection and loose coupling
      category: Service Layer
      
    - name: core-sdk.service-container.md
      description: Service container pattern for dependency injection and lifecycle management
      category: Service Layer
      
    - name: core-sdk.service-error-handling.md
      description: Consistent error handling pattern with custom error classes and error codes
      category: Service Layer
      
    - name: core-sdk.service-logging.md
      description: Structured logging pattern with consistent format across services
      category: Service Layer
    
    - name: core-sdk.adapter-base.md
      description: Base adapter class pattern with lifecycle management for all deployment targets
      category: Adapter Layer
      
    - name: core-sdk.adapter-mcp.md
      description: MCP adapter pattern for exposing services through Model Context Protocol
      category: Adapter Layer
      
    - name: core-sdk.adapter-rest.md
      description: REST adapter pattern for exposing services through HTTP REST APIs
      category: Adapter Layer
      
    - name: core-sdk.adapter-cli.md
      description: CLI adapter pattern for exposing services through command-line interfaces
      category: Adapter Layer
      
    - name: core-sdk.adapter-client.md
      description: Client adapter pattern for exposing services as a consumable library
      category: Adapter Layer

    - name: core-sdk.config-schema.md
      description: Type-safe configuration schema pattern using Zod with validation and composition
      category: Configuration

    - name: core-sdk.config-environment.md
      description: Environment variable mapping pattern with type coercion and naming conventions
      category: Configuration

    - name: core-sdk.config-loading.md
      description: Layered configuration loading pattern with priority hierarchy and hot reload
      category: Configuration

    - name: core-sdk.config-secrets.md
      description: Secret management pattern with Secret wrapper, vault integration, and rotation
      category: Configuration

    - name: core-sdk.config-multi-env.md
      description: Multi-environment configuration pattern with inheritance for dev/staging/prod
      category: Configuration

  commands: []
  
  designs:
    - name: core-sdk.architecture.md
      description: Patterns and templates for creating reusable core libraries that can be shared across MCP servers, REST APIs, and client applications
  
  # Template source files for core library projects
  templates:
    # Configuration templates
    - name: config/package.json.template
      description: npm package configuration with subpath exports
      target: ./
      required: true
      variables:
        - PACKAGE_NAME
        - PACKAGE_DESCRIPTION
        - AUTHOR_NAME
    
    - name: config/tsconfig.json
      description: TypeScript configuration for ESM modules
      target: ./
      required: true
    
    - name: config/jest.config.js
      description: Jest configuration for ESM + TypeScript
      target: ./
      required: true
    
    - name: config/esbuild.build.js
      description: esbuild build configuration for multiple entry points
      target: ./
      required: true
    
    - name: config/esbuild.watch.js
      description: esbuild watch mode for development
      target: ./
      required: true
    
    - name: config/gitignore.template
      description: Git ignore rules for Node.js projects
      target: ./.gitignore
      required: true
    
    - name: config/npmignore.template
      description: npm ignore rules to exclude dev files
      target: ./.npmignore
      required: true
    
    # Source code templates
    - name: src/schemas/example.schema.ts
      description: Example Zod schema with TypeScript type inference
      target: src/schemas/
      required: false
    
    - name: src/services/example.service.ts
      description: Example service layer for Firestore operations
      target: src/services/
      required: false
    
    - name: src/dto/example.dto.ts
      description: Example DTO type definitions
      target: src/dto/
      required: false
    
    - name: src/dto/transformers.ts
      description: DTO transformer functions
      target: src/dto/
      required: false
    
    - name: src/dto/index.ts
      description: Centralized DTO exports
      target: src/dto/
      required: false
    
    - name: src/constant/collections.ts
      description: Firestore collection path helpers
      target: src/constant/
      required: false
    
    - name: src/errors/index.ts
      description: Error exports and utilities
      target: src/errors/
      required: false
    
    - name: src/errors/task-errors.ts
      description: Custom error classes with HTTP status codes
      target: src/errors/
      required: false
    
    - name: src/errors/task-errors.spec.ts
      description: Error class tests
      target: src/errors/
      required: false
    
    - name: src/client.ts
      description: Client wrapper for multi-tenant access
      target: src/
      required: false

# Compatibility
requires:
  acp: >=2.8.0

# Tags for discovery
tags:
  - core-library
  - sdk
  - typescript
  - npm-package
  - mcp
  - rest-api
  - reusable-code
